# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(893, 442)
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(550, 40, 160, 147))
        self.label_1.setText("")
        self.label_1.setPixmap(QtGui.QPixmap("./image/person.png"))
        self.label_1.setScaledContents(True)
        self.label_1.setObjectName("label_1")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(550, 249, 160, 147))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("./image/person.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(720, 249, 160, 147))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("./image/person.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(720, 40, 160, 147))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("./image/person.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.text_1 = QtWidgets.QLabel(Form)
        self.text_1.setGeometry(QtCore.QRect(550, 11, 160, 16))
        self.text_1.setAlignment(QtCore.Qt.AlignCenter)
        self.text_1.setObjectName("text_1")
        self.text_3 = QtWidgets.QLabel(Form)
        self.text_3.setGeometry(QtCore.QRect(550, 220, 160, 16))
        self.text_3.setAlignment(QtCore.Qt.AlignCenter)
        self.text_3.setObjectName("text_3")
        self.text_2 = QtWidgets.QLabel(Form)
        self.text_2.setGeometry(QtCore.QRect(720, 11, 160, 16))
        self.text_2.setAlignment(QtCore.Qt.AlignCenter)
        self.text_2.setObjectName("text_2")
        self.text_4 = QtWidgets.QLabel(Form)
        self.text_4.setGeometry(QtCore.QRect(720, 220, 160, 16))
        self.text_4.setAlignment(QtCore.Qt.AlignCenter)
        self.text_4.setObjectName("text_4")
        self.image_label = QtWidgets.QLabel(Form)
        self.image_label.setGeometry(QtCore.QRect(10, 10, 525, 386))
        self.image_label.setText("")
        self.image_label.setPixmap(QtGui.QPixmap("./image/camera.png"))
        self.image_label.setScaledContents(True)
        self.image_label.setObjectName("image_label")
        self.control_bt = QtWidgets.QPushButton(Form)
        self.control_bt.setGeometry(QtCore.QRect(10, 405, 871, 28))
        self.control_bt.setObjectName("control_bt")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cam view"))
        self.text_1.setText(_translate("Form", "TextLabel"))
        self.text_3.setText(_translate("Form", "TextLabel"))
        self.text_2.setText(_translate("Form", "TextLabel"))
        self.text_4.setText(_translate("Form", "TextLabel"))
        self.control_bt.setText(_translate("Form", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
