# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1551, 778)
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(1300, 10, 241, 136))
        self.label_1.setText("")
        self.label_1.setPixmap(QtGui.QPixmap("../demo/image/person.png"))
        self.label_1.setScaledContents(True)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(1300, 156, 241, 136))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../demo/image/person.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(1300, 448, 241, 136))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../demo/image/person.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(1300, 302, 241, 136))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../demo/image/person.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(1300, 594, 241, 136))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../demo/image/person.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.image_label = QtWidgets.QLabel(Form)
        self.image_label.setGeometry(QtCore.QRect(10, 10, 1280, 720))
        self.image_label.setText("")
        self.image_label.setPixmap(QtGui.QPixmap("../demo/image/camera.png"))
        self.image_label.setScaledContents(True)
        self.image_label.setObjectName("image_label")
        self.control_bt = QtWidgets.QPushButton(Form)
        self.control_bt.setGeometry(QtCore.QRect(10, 740, 1531, 28))
        self.control_bt.setObjectName("control_bt")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cam view"))
        self.control_bt.setText(_translate("Form", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
